version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  unleash:
    image: unleashorg/unleash-server:4.20.4
    ports:
      - "4242:4242"
    environment:
      INIT_CLIENT_API_TOKENS: "*:development:some-secret"
      DATABASE_URL: "postgres://postgres:unleash@db/postgres"
      DATABASE_SSL: "false"

  db:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    command: index.js
    ports:
      - "5000:5000"
    depends_on:
      - redis


